/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myproject;

import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void GCDEuclidSubtractionRec_test() {
        Assert.assertEquals(1,1);
    }
}
